# paths.yaml
# Centralisation de tous les chemins utilisÃ©s dans le projet.

data:
  root: "data/"

  input:
    raw_dataset: "data/raw/diabetes_health_indicators.csv"
    train_dataset: "data/input/train.csv"
    test_dataset: "data/input/test.csv"

  processed:
    cleaned_dataset: "data/processed/cleaned_diabetes.csv"
    features_dataset: "data/processed/features_diabetes.csv"

  output:
    model: "data/output/model.pkl"
    pipeline: "data/output/pipeline.pkl"

reports:
  eda_report: "reports/eda_reports"
  metrics_report: "reports/metrics"
  curves_reports: "reports/figures"
  cm_reports: "reports/cm"

logs:
  folder: "logs"
  main_log: "logs/app.log"
