name: CI - Health Lifestyle Diabetes Project

on:
  push:
    branches: [ main , code_quality_clean_arch]
  pull_request:
    branches: [ main , code_quality_clean_arch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ§ª Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: ğŸ“š Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: ğŸ§¹ Lint with Ruff
        run: |
          poetry run ruff check .

      - name: ğŸ§¼ Format check with Black
        run: |
          poetry run black --check .

      - name: ğŸ” Run unit tests
        run: |
          poetry run pytest --disable-warnings --maxfail=1

      - name: ğŸ“¦ Build package
        run: |
          poetry build
